# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
import '../../fastlane/Utils'

default_platform(:mac)

platform :mac do
  desc "Push a new release build to the App Store"
  lane :release do
    apple_build("macos")
    upload_to_app_store(
      build_number: version_code
    )
  end

  desc "Push a new release build to TestFlight"
  lane :beta do
    apple_build("macos")
    upload_to_testflight(
      build_number: version_code
    )
  end
end
